apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "crud-app-chart.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: arch.homework
      http:
        paths:
          - path: /otusapp/evdoshenko(/?)(.*)
            backend:
              serviceName: {{ include "crud-app-chart.fullname" . }}
              servicePort: {{ .Values.service.port }}