apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "order-app-chart.fullname" . }}
data:
  MONGO_PORT: {{.Values.mongodb.service.port | quote}}
  MONGO_HOST: {{ .Release.Name }}-mongodb
  MONGO_DATABASE: {{.Values.mongodb.mongodbDatabase | quote}}
---
apiVersion: v1
kind: Secret
metadata:
  name: order-app-secret
type: Opaque
data:
  MONGO_USERNAME: {{.Values.mongodb.mongodbUsername | b64enc | quote}}
  MONGO_PASSWORD: {{.Values.mongodb.mongodbPassword | b64enc | quote}}