apiVersion: v2
name: crud-app-chart
description: A Helm chart for Kubernetes for crud-app
type: application
version: 0.1.0
appVersion: v1

dependencies:
  - name: mongodb
    version: 7.11.x
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
    tags:
      - homework-database